### ISSUE TITLE
Can't generate entities 

### ISSUE THREAD

**Issue by tung1404** [mikro-orm/nestjs-realworld-example-app#69]
When I run `yarn mikro-orm generate-entities --dump`
It throw error 

```
Error: Cannot find module 'C:\Users\user\Downloads\_git\nodejs-api\nestjs-realworld-example-app\@mikro-orm\entity-generator'
Require stack:
- C:\Users\user\Downloads\_git\nodejs-api\nestjs-realworld-example-app\__fake.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Users\user\Downloads\_git\nodejs-api\nestjs-realworld-example-app\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Function.requireFrom (C:\Users\user\Downloads\_git\nodejs-api\nestjs-realworld-example-app\node_modules\@mikro-orm\core\utils\Utils.js:692:70)    
    at Function.options.dynamicImportProvider.options.dynamicImportProvider [as dynamicImportProvider] (C:\Users\user\Downloads\_git\nodejs-api\nestjs-realworld-example-app\node_modules\@mikro-orm\core\utils\ConfigurationLoader.js:219:34)
    at Function.dynamicImport (C:\Users\user\Downloads\_git\nodejs-api\nestjs-realworld-example-app\node_modules\@mikro-orm\core\utils\Utils.js:713:32)  
    at Object.handler (C:\Users\user\Downloads\_git\nodejs-api\nestjs-realworld-example-app\node_modules\@mikro-orm\cli\commands\GenerateEntitiesCommand.js:44:56)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\Downloads\\_git\\nodejs-api\\nestjs-realworld-example-app\\__fake.js'
  ]
}
```

**Comment by B4nan** [comment]
Because you need to install the entity generator package first.

**Comment by tung1404** [comment]
I try to install entity-generator but it is still not working.
Please try to run `yarn mikro-orm generate-entities --dump` and confirm it works!
